Highcharts.setOptions({
    lang: {
        thousandsSep: ','
    }
});

  var chartRate = new Highcharts.Chart({
      chart: {
        renderTo: 'graphic',
        backgroundColor: '#fafafa',
        width: w,
        height: '80%',
        spacingBottom: 15,
        spacingTop: 10,
        spacingLeft: 10,
        spacingRight: 10,
        type: 'tilemap',
        inverted: true
      },
      title: {
            text: null,
      },
      credits: {
          enabled: false
      },
      xAxis: {
        visible: false
      },
      yAxis: {
        visible: false
      },
      legend: {
        reversed: false
      },
      colorAxis: {
        dataClasses: [{
            from: 0,
            to: 12.2,
            color: '#FFE5C2',
            name: '< 12.2 per 100,000'
        }, {
            from: 12.3,
            to: 18,
            color: '#FFD387',//#FFCE7B
            name: '12.3 to 18'
        }, {
            from: 18.1,
            to: 23.2,
            color: '#EBAB38',
            name: '18.2 to 23.2'
        }, {
            from: 23.3,
            to: 30.9,
            color: '#DF896F',
            name: '23.3 to 30.9'
        }, {
            from: 31,
            to: 60,
            color: '#AE1B1F',
            name: '> 31 per 100,000'
        }, {
            from: -1,
            to: 0,
            color: "#DDDDDD",
            name: "No Data"
        }]
      },
      tooltip: {
        useHTML: true,
        headerFormat: '<h5><b>{point.key}</b></h5>',
        //headerFormat: '{point.name}',
        pointFormat: '<ul><li>Drug overdose death rate<br>per 100,000: <b>{point.legend}</b></li><li>Deaths:  <b>{point.deaths}</b></li>'
      },
      plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                format: '{point.hc-a2}',
                //color: '#000000',
                style: {
                    textOutline: false
                },
                formatter: function() {
                        var max = this.series.yAxis.max,
                            color =  this.y / max < 0.05 ? 'black' : 'white';
                            //GlobalRotation = this.y / max < 0.05 ? 0 : -90;
                            //GlobalAlign = this.y / max < 0.05 ? 'left' : 'right';
                            //X = this.y / max < 0.05 ? 4 : 4;
                            //Y = this.y / max < 0.05 ? 0 : 5;
                        return '<span style="color: ' + color + '">' + this.y + ' </span>';
                }
            }
        }
      },
      series: [{
        name: '',
        data: [{
            'hc-a2': 'AL',
            name: 'Alabama',
            region: 'South',
            x: 6,
            y: 7,
            value: parseFloat(DATA[0].value),
            legend: DATA[0].legend,
            deaths: DATA[0].deaths
        }, {
            'hc-a2': 'AK',
            name: 'Alaska',
            region: 'West',
            x: 0,
            y: 0,
            value: parseFloat(DATA[1].value),
            legend: DATA[1].legend,
            deaths: DATA[1].deaths
        }, {
            'hc-a2': 'AZ',
            name: 'Arizona',
            region: 'West',
            x: 5,
            y: 3,
            value: parseFloat(DATA[2].value),
            legend: DATA[2].legend,
            deaths: DATA[2].deaths
        }, {
            'hc-a2': 'AR',
            name: 'Arkansas',
            region: 'South',
            x: 5,
            y: 6,
            value: parseFloat(DATA[3].value),
            legend: DATA[3].legend,
            deaths: DATA[3].deaths
        }, {
            'hc-a2': 'CA',
            name: 'California',
            region: 'West',
            x: 5,
            y: 2,
            value: parseFloat(DATA[4].value),
            legend: DATA[4].legend,
            deaths: DATA[4].deaths
        }, {
            'hc-a2': 'CO',
            name: 'Colorado',
            region: 'West',
            x: 4,
            y: 3,
            value: parseFloat(DATA[5].value),
            legend: DATA[5].legend,
            deaths: DATA[5].deaths
        }, {
            'hc-a2': 'CT',
            name: 'Connecticut',
            region: 'Northeast',
            x: 3,
            y: 11,
            value: parseFloat(DATA[6].value),
            legend: DATA[6].legend,
            deaths: DATA[6].deaths
        }, {
            'hc-a2': 'DE',
            name: 'Delaware',
            region: 'South',
            x: 4,
            y: 9,
            value: parseFloat(DATA[7].value),
            legend: DATA[7].legend,
            deaths: DATA[7].deaths
        }, {
            'hc-a2': 'DC',
            name: 'District of Columbia',
            region: 'South',
            x: 4,
            y: 10,
            value: parseFloat(DATA[8].value),
            legend: DATA[8].legend,
            deaths: DATA[8].deaths
        }, {
            'hc-a2': 'FL',
            name: 'Florida',
            region: 'South',
            x: 8,
            y: 8,
            value: parseFloat(DATA[9].value),
            legend: DATA[9].legend,
            deaths: DATA[9].deaths
        }, {
            'hc-a2': 'GA',
            name: 'Georgia',
            region: 'South',
            x: 7,
            y: 8,
            value: parseFloat(DATA[10].value),
            legend: DATA[10].legend,
            deaths: DATA[10].deaths
        }, {
            'hc-a2': 'HI',
            name: 'Hawaii',
            region: 'West',
            x: 8,
            y: 0,
            value: parseFloat(DATA[11].value),
            legend: DATA[11].legend,
            deaths: DATA[11].deaths
        }, {
            'hc-a2': 'ID',
            name: 'Idaho',
            region: 'West',
            x: 3,
            y: 2,
            value: parseFloat(DATA[12].value),
            legend: DATA[12].legend,
            deaths: DATA[12].deaths
        }, {
            'hc-a2': 'IL',
            name: 'Illinois',
            region: 'Midwest',
            x: 3,
            y: 6,
            value: parseFloat(DATA[13].value),
            legend: DATA[13].legend,
            deaths: DATA[13].deaths
        }, {
            'hc-a2': 'IN',
            name: 'Indiana',
            region: 'Midwest',
            x: 3,
            y: 7,
            value: parseFloat(DATA[14].value),
            legend: DATA[14].legend,
            deaths: DATA[14].deaths
        }, {
            'hc-a2': 'IA',
            name: 'Iowa',
            region: 'Midwest',
            x: 3,
            y: 5,
            value: parseFloat(DATA[15].value),
            legend: DATA[15].legend,
            deaths: DATA[15].deaths
        }, {
            'hc-a2': 'KS',
            name: 'Kansas',
            region: 'Midwest',
            x: 5,
            y: 5,
            value: parseFloat(DATA[16].value),
            legend: DATA[16].legend,
            deaths: DATA[16].deaths
        }, {
            'hc-a2': 'KY',
            name: 'Kentucky',
            region: 'South',
            x: 4,
            y: 6,
            value: parseFloat(DATA[17].value),
            legend: DATA[17].legend,
            deaths: DATA[17].deaths
        }, {
            'hc-a2': 'LA',
            name: 'Louisiana',
            region: 'South',
            x: 6,
            y: 5,
            value: parseFloat(DATA[18].value),
            legend: DATA[18].legend,
            deaths: DATA[18].deaths
        }, {
            'hc-a2': 'ME',
            name: 'Maine',
            region: 'Northeast',
            x: 0,
            y: 11,
            value: parseFloat(DATA[19].value),
            legend: DATA[19].legend,
            deaths: DATA[19].deaths
        }, {
            'hc-a2': 'MD',
            name: 'Maryland',
            region: 'South',
            x: 4,
            y: 8,
            value: parseFloat(DATA[20].value),
            legend: DATA[20].legend,
            deaths: DATA[20].deaths
        }, {
            'hc-a2': 'MA',
            name: 'Massachusetts',
            region: 'Northeast',
            x: 2,
            y: 10,
            value: parseFloat(DATA[21].value),
            legend: DATA[21].legend,
            deaths: DATA[21].deaths
        }, {
            'hc-a2': 'MI',
            name: 'Michigan',
            region: 'Midwest',
            x: 2,
            y: 7,
            value: parseFloat(DATA[22].value),
            legend: DATA[22].legend,
            deaths: DATA[22].deaths
        }, {
            'hc-a2': 'MN',
            name: 'Minnesota',
            region: 'Midwest',
            x: 2,
            y: 4,
            value: parseFloat(DATA[23].value),
            legend: DATA[23].legend,
            deaths: DATA[23].deaths
        }, {
            'hc-a2': 'MS',
            name: 'Mississippi',
            region: 'South',
            x: 6,
            y: 6,
            value: parseFloat(DATA[24].value),
            legend: DATA[24].legend,
            deaths: DATA[24].deaths
        }, {
            'hc-a2': 'MO',
            name: 'Missouri',
            region: 'Midwest',
            x: 4,
            y: 5,
            value: parseFloat(DATA[25].value),
            legend: DATA[25].legend,
            deaths: DATA[25].deaths
        }, {
            'hc-a2': 'MT',
            name: 'Montana',
            region: 'West',
            x: 2,
            y: 2,
            value: parseFloat(DATA[26].value),
            legend: DATA[26].legend,
            deaths: DATA[26].deaths
        }, {
            'hc-a2': 'NE',
            name: 'Nebraska',
            region: 'Midwest',
            x: 4,
            y: 4,
            value: parseFloat(DATA[27].value),
            legend: DATA[27].legend,
            deaths: DATA[27].deaths
        }, {
            'hc-a2': 'NV',
            name: 'Nevada',
            region: 'West',
            x: 4,
            y: 2,
            value: parseFloat(DATA[28].value),
            legend: DATA[28].legend,
            deaths: DATA[28].deaths
        }, {
            'hc-a2': 'NH',
            name: 'New Hampshire',
            region: 'Northeast',
            x: 1,
            y: 11,
            value: parseFloat(DATA[29].value),
            legend: DATA[29].legend,
            deaths: DATA[29].deaths
        }, {
            'hc-a2': 'NJ',
            name: 'New Jersey',
            region: 'Northeast',
            x: 3,
            y: 10,
            value: parseFloat(DATA[30].value),
            legend: DATA[30].legend,
            deaths: DATA[30].deaths
        }, {
            'hc-a2': 'NM',
            name: 'New Mexico',
            region: 'West',
            x: 6,
            y: 3,
            value: parseFloat(DATA[31].value),
            legend: DATA[31].legend,
            deaths: DATA[31].deaths
        }, {
            'hc-a2': 'NY',
            name: 'New York',
            region: 'Northeast',
            x: 2,
            y: 9,
            value: parseFloat(DATA[32].value),
            legend: DATA[32].legend,
            deaths: DATA[32].deaths
        }, {
            'hc-a2': 'NC',
            name: 'North Carolina',
            region: 'South',
            x: 5,
            y: 9,
            value: parseFloat(DATA[33].value),
            legend: DATA[33].legend,
            deaths: DATA[33].deaths
        }, {
            'hc-a2': 'ND',
            name: 'North Dakota',
            region: 'Midwest',
            x: 2,
            y: 3,
            value: parseFloat(DATA[34].value),
            legend: DATA[34].legend,
            deaths: DATA[34].deaths
        }, {
            'hc-a2': 'OH',
            name: 'Ohio',
            region: 'Midwest',
            x: 3,
            y: 8,
            value: parseFloat(DATA[35].value),
            legend: DATA[35].legend,
            deaths: DATA[35].deaths
        }, {
            'hc-a2': 'OK',
            name: 'Oklahoma',
            region: 'South',
            x: 6,
            y: 4,
            value: parseFloat(DATA[36].value),
            legend: DATA[36].legend,
            deaths: DATA[36].deaths
        }, {
            'hc-a2': 'OR',
            name: 'Oregon',
            region: 'West',
            x: 4,
            y: 1,
            value: parseFloat(DATA[37].value),
            legend: DATA[37].legend,
            deaths: DATA[37].deaths
        }, {
            'hc-a2': 'PA',
            name: 'Pennsylvania',
            region: 'Northeast',
            x: 3,
            y: 9,
            value: parseFloat(DATA[38].value),
            legend: DATA[38].legend,
            deaths: DATA[38].deaths
        }, {
            'hc-a2': 'RI',
            name: 'Rhode Island',
            region: 'Northeast',
            x: 2,
            y: 11,
            value: parseFloat(DATA[39].value),
            legend: DATA[39].legend,
            deaths: DATA[39].deaths
        }, {
            'hc-a2': 'SC',
            name: 'South Carolina',
            region: 'South',
            x: 6,
            y: 8,
            value: parseFloat(DATA[40].value),
            legend: DATA[40].legend,
            deaths: DATA[40].deaths
        }, {
            'hc-a2': 'SD',
            name: 'South Dakota',
            region: 'Midwest',
            x: 3,
            y: 4,
            value: parseFloat(DATA[41].value),
            legend: DATA[41].legend,
            deaths: DATA[41].deaths
        }, {
            'hc-a2': 'TN',
            name: 'Tennessee',
            region: 'South',
            x: 5,
            y: 7,
            value: parseFloat(DATA[42].value),
            legend: DATA[42].legend,
            deaths: DATA[42].deaths
        }, {
            'hc-a2': 'TX',
            name: 'Texas',
            region: 'South',
            x: 7,
            y: 4,
            value: parseFloat(DATA[43].value),
            legend: DATA[43].legend,
            deaths: DATA[43].deaths
        }, {
            'hc-a2': 'UT',
            name: 'Utah',
            region: 'West',
            x: 5,
            y: 4,
            value: parseFloat(DATA[44].value),
            legend: DATA[44].legend,
            deaths: DATA[44].deaths
        }, {
            'hc-a2': 'VT',
            name: 'Vermont',
            region: 'Northeast',
            x: 1,
            y: 10,
            value: parseFloat(DATA[45].value),
            legend: DATA[45].legend,
            deaths: DATA[45].deaths
        }, {
            'hc-a2': 'VA',
            name: 'Virginia',
            region: 'South',
            x: 5,
            y: 8,
            value: parseFloat(DATA[46].value),
            legend: DATA[46].legend,
            deaths: DATA[46].deaths
        }, {
            'hc-a2': 'WA',
            name: 'Washington',
            region: 'West',
            x: 2,
            y: 1,
            value: parseFloat(DATA[47].value),
            legend: DATA[47].legend,
            deaths: DATA[47].deaths
        }, {
            'hc-a2': 'WV',
            name: 'West Virginia',
            region: 'South',
            x: 4,
            y: 7,
            value: parseFloat(DATA[48].value),
            legend: DATA[48].legend,
            deaths: DATA[48].deaths
        }, {
            'hc-a2': 'WI',
            name: 'Wisconsin',
            region: 'Midwest',
            x: 2,
            y: 5,
            value: parseFloat(DATA[49].value),
            legend: DATA[49].legend,
            deaths: DATA[49].deaths
        }, {
            'hc-a2': 'WY',
            name: 'Wyoming',
            region: 'West',
            x: 3,
            y: 3,
            value: parseFloat(DATA[50].value),
            legend: DATA[50].legend,
            deaths: DATA[50].deaths
        }]
      }]

//End
  });
